### ISSUE TITLE
Houses missing resource forks

### ISSUE THREAD

**Issue by cuavas** [softdorothy/glider_pro#1]
The checked-in house files are missing the resource forks which contain PICT assets.  In my copy of Glider Pro, Slumberland has a 131KiB data fork and a 1016KiB resource fork.  Only the data fork appears to be checked in.

Also, the quicktime movies are missing the resource forks which contain the moov atom.  Quicktime supports storing the resource in a separate .qtr file, or flattening the files to a single stream.

**Comment by softdorothy** [comment]
Thanks, it looks like this will be more work to get right. (sigh) I'll see what I can figure out. I hope I don;t have to binhex then macbinary for the resource forks....

**Comment by cuavas** [comment]
This tool can flatten quicktime movies:
https://github.com/bangnoise/qt-flatten

Why don't you just run DeRez on the houses and check in a .r file beside each one?

**Comment by softdorothy** [comment]
Is there a DeRez that still runs on OS X? I assumed a tool like that would be long gone.

**Comment by cuavas** [comment]
DeRez is still present in Xcode tools with OSX 10.6 - not sure if it's supplied with more recent Xcode but you should be able to run the 10.6 version on latest OSX (Xcode 3).

**Comment by softdorothy** [comment]
Awesome. Thanks.

**Comment by softdorothy** [comment]
I just committed a new Slumberland house, binhexed.  Sizewise it looks good.

**Comment by elasota** [comment]
QuickTime movies are still missing resource fork data.  They can't be played without it since the moov resource contains the image format/tracking info.  (Demo House.mov is the only exception, it contains a duplicate in the data fork.)
